### PR TITLE
Adding missing query field to writeQuery

### PR DESCRIPTION
**Pull request by yattias**
In reference to https://github.com/apollographql/react-apollo/issues/568

### CODE REVIEW

**Comment by helfer** [comment]
@yattias that notation is actually perfectly well formatted ES 6 using an [Object Literal Property Value Shorthand](https://ariya.io/2013/02/es6-and-object-literal-property-value-shorthand). What problem did you encounter with it? Is it not clear what it does?

**Comment by yattias** [comment]
Hey @helfer that makes sense - I actually was not aware of the shorthand notation.

That being said, I am still getting an error `cannot read property "kind" of undefined`

My code:

```js
      const data = client.writeQuery({
        getUserAssetsQuery,
        data: {
          assets: [{id: id}, ...currentAssets]
        }
      });
```

**Comment by helfer** [comment]
@yattias do you only get that error if you use the shorthand notation? I think a PR to apollo-client that throws a better error message if the query is missing would be really useful. Could you do that?

**Comment by helfer** [comment]
Closing since this is an old PR.

**Pull request closed without merging**
