### PR TITLE
Distinguish types of batching

### PR DESCRIPTION
**Pull request by djshapiro**
I didn't realize at first that query-level and transport-level batching were two different things. I tried to make that more explicit here. The docs still need an example of how to turn transport-level batching on in the client.

According to the comment on lines 22-25 of https://github.com/apollostack/apollo-client/blob/master/src/transport/batchedNetworkInterface.ts, it looks like batchedNetworkInterface handles transport-level batching and something called addQueryMerging (which I can't find in the code) turns on query-level batching. Is that correct? If so, I can update the docs as part of this PR.

### CODE REVIEW

**Comment by helfer** [comment]
@djshapiro Thanks for the PR! The thing called queryMerging no longer exists, so it would be great if you could remove that part altogether!

**Comment by djshapiro** [comment]
@helfer Alright, I will make those changes at some point in the near future.

**Comment by helfer** [comment]
@djshapiro bump :)

**Comment by helfer** [comment]
Did it myself, will merge now.

**Pull request merged**
