### PR TITLE
Add docs for the exposure of 'dataIdFromObject' and 'dataId'

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
As discussed in [apollographql/apollo-client#1657 (comment)](https://github.com/apollographql/apollo-client/issues/1657#issuecomment-299536799)

Merge after apollographql/react-docs#221

CC: @helfer

### CODE REVIEW

**Comment by helfer** [comment]
Thanks!

**Comment by MichaelDeBoey** [comment]
Looks like this isn't live yet?
Or did I something wrong? 😕

**Comment by helfer** [comment]
Yeah, it looks like the deploy is currently broken because of a dependency.

**Comment by MichaelDeBoey** [comment]
Oh OK, not my fault then? 🙂

**Comment by helfer** [comment]
No, definitely not your fault.

**Comment by MichaelDeBoey** [comment]
@helfer Still broken? 😕

**Pull request merged**
