### PR TITLE
Updated subscriptions docs 

### PR DESCRIPTION
**Pull request by dotansimha**
Added WebSocket network interface using `subscriptions-transport-ws`.

Also, updated git submodule to latest to fix https://github.com/apollographql/core-docs/issues/277

### CODE REVIEW

**Comment by helfer** [comment]
Thanks a lot @dotansimha !

**Comment by helfer** [comment]
Oh noes, the build on circle CI still fails.

**Comment by dotansimha** [comment]
@helfer maybe it's CI cache of the `master` branch? (https://github.com/apollographql/core-docs/blob/master/circle.yml#L10-L11)
In my branch the CI worked.

**Comment by ignacio-chiazzo** [comment]
Is it the same issue that I am having? https://github.com/apollographql/core-docs/pull/323. Shall we remove the cache as @dotansimha said?

**Pull request merged**
