### PR TITLE
Update Meteor docs about subscriptions

### PR DESCRIPTION
**Pull request by xavcz**
Related to https://github.com/apollographql/meteor-integration/pull/85, here is an update of the Meteor docs to explain how to use GraphQL subscriptions 🎉 

It shows another example for subscriptions, to not overkill the basic example; and document the client/server exported functions.

### CODE REVIEW

**Comment by helfer** [comment]
Thanks @xavcz! Is the `PubSub` that comes with the package actually something that can run in production, or should we also point people towards some info on how to wire it up with Redis, MQTT or some package that uses the mongo oplog (I think there's some potential here for a new custom package).

**Comment by xavcz** [comment]
Mmmh, we currently only tell folks about `PubSub` from `graphql-subscriptions`: I believe it can be used in production, several companies are running with that, aren't they? 😃 

My knowledge concerning other pub/sub systems around there is fairly limited, apart what we leverage in Meteor with Mongo; yet I believe that yes, there is room for wiring this package with other systems. I expect the `meteor/apollo` package to allow soon to use easily packages like `meteor-rx`, `graphql-rx` & maybe other systems. 

Folks with more knowledge in these domains trying that seem like: 🔥 I'll ask about that when doing promo about `meteor/apollo` in the Meteor forums :)

**Comment by helfer** [comment]
The problem with that package is that it uses event emitters, which under the default setting (which we use) can't have more than 5 or 10 listeners. It also doesn't broadcast events beyond a single server, so I'm pretty sure people don't use that in production. It's really just for small demos or testing. For production there are the packages that integrate it with Redis and MQTT.

**Comment by xavcz** [comment]
Holy cow, yes! So seems fair to not shout from the rooftops and provide a more reliable solution!

Thanks a lot for the heads up!! 💯

**Comment by stubailo** [comment]
I think we can merge this if we just add a link to something like https://github.com/davidyaha/graphql-redis-subscriptions

**Comment by xavcz** [comment]
`meteor/apollo` is taking the direction of staying simple (see PR referenced above for more detailed explanations 🙂). 

➡️ We are going to create a new package leveraging observables to help Meteor folks get the most out of the GraphQL subscriptions. 

I believe it's a good idea to close this one and keep it as a reference for an upcoming PR to the docs that will explain how to use this upcoming package.

**Pull request closed without merging**
